Schastlivtsev.nikita
pv6/OS_Labs_SPBPU_2020 pull request #1
Opened 2020-10-24 11:26 UTC by NikitaS4

2020-10-25 14:42 UTC, pv6 requested changes

2020-10-25 14:42 UTC, pv6 commented on schastlivtsev.nikita/lab1/DaemonCreator.cpp
> +        exit(1); // session creation failed
Почему exit(1), а не исключение?

2020-10-25 14:42 UTC, pv6 commented on schastlivtsev.nikita/lab1/DaemonCreator.cpp
> +        exit(0);
Не стоит использовать exit(0) для остановки родительского процесса так как:
- Родительский процесс, в общем случае, может и продолжать работу после запуска демона
- exit сразу закрывает программу, без развертывания стека и вызова соответствующих деструкторов. Так что в родительском процессе происходит утечка памяти

Надо обернуть весь запуск демона (включая создание Логгера, парсинг конфига и т.д.) в одну функцию, вызываемую в main, а после неё родительский процесс уже либо завершается, либо в общем случае делает что ему дальше нужно.

2020-10-25 14:42 UTC, pv6 commented on schastlivtsev.nikita/lab1/Helpers.cpp
> +}
Почему не используете std::string для хранения строк?

2020-10-25 14:42 UTC, pv6 commented on schastlivtsev.nikita/lab1/SignalHandler.h
> +        signalHandlerFunc getSighupHandler();
Все эти функции могут быть static. В таком случае класс SignalHandler лучше сделать синглтоном.

2020-10-25 14:42 UTC, pv6 commented on schastlivtsev.nikita/lab1/main.cpp
> +        settingsManager.updateSettings(); // parse config and set values to start
Все эти действия следовало бы делать только в дочернем процессе

2020-10-25 14:42 UTC, pv6 commented on schastlivtsev.nikita/lab1/SignalHandler.cpp
> +    }
exit(0) здесь опять же приведет к потере памяти

2020-10-26 15:27 UTC, NikitaS4 commented on schastlivtsev.nikita/lab1/DaemonCreator.cpp
> +        exit(1); // session creation failed
Исправил, теперь исключение

2020-10-26 15:29 UTC, NikitaS4 commented on schastlivtsev.nikita/lab1/DaemonCreator.cpp
> +        exit(0);
Не знал, что происходит утечка памяти, читал гайды для кода на Си. Исправил, теперь цепочкой `return`'ов исполнение доходит до `main`, где корректно завершается.

2020-10-26 15:30 UTC, NikitaS4 commented on schastlivtsev.nikita/lab1/SignalHandler.h
> +        signalHandlerFunc getSighupHandler();
Сделал эти функции `static`. Нужды в том, чтобы это был синглтон, не оказалось, класс сделал полностью статическим.

2020-10-26 15:33 UTC, NikitaS4 commented on schastlivtsev.nikita/lab1/main.cpp
> +        settingsManager.updateSettings(); // parse config and set values to start
Поправил, поместил по максимуму всё это в дочерний процесс. Создание экземпляра `SettingsManager` не удалось избежать, так как он нужен для создания обработчиков сигналов. Однако его "честную" инициализацию (чтение config'а) отложил до дочернего процесса.

2020-10-26 15:33 UTC, NikitaS4 commented on schastlivtsev.nikita/lab1/SignalHandler.cpp
> +    }
Спасибо, поправил.

2020-10-26 15:35 UTC, NikitaS4 commented on schastlivtsev.nikita/lab1/Helpers.cpp
> +}
Хотелось использовать указатели в `Settings`, чтобы с помощью проверки на `nullptr` знать, когда соответствующее поле не заполнено.

2020-10-28 15:33 UTC, merged