Krupkina.daria lab2
pv6/OS_Labs_SPBPU_2020 pull request #34
Opened 2020-11-26 18:54 UTC by DariaKrup

2020-11-28 14:08 UTC, pv6 requested changes
Как я понял вашу текущую структуру:
1) Хост, через client_host_connection, посылает client_handler-у сообщение
2) Затем client_handler, работающий в отдельном потоке, пересылает это сообщение процессу-клиенту через класс conn, получает ответ, и выводит на экран

Связывать хост с потоком через client_host_connection в виде pipe нет необходимости, так как они и так шарят свою память (вы это уже используете, когда обращаетесь в функции execute по указателю к хэндлеру). Так что передавать сообщение (а лучше дату напрямую, и преобразовывать в сообщение уже в клиент_хэндлере) можно просто записывая значение в поле хендлера. Либо записывая в поле сервера, и читать в хендлере по server.getInstance()->date;

Синхронизация между хостом и хендлерами чере bool переменную, как у вас сейчас, вполне рабочий вариант.

2020-11-28 14:08 UTC, pv6 commented on lab2/host/server.h
> +    server();
Для синглтона следует также заприватить конструктор копирования и оператор=. Публичный оператор присваивания как у вас — технически безобиден, но считается для синглтона плохим стилем.

2020-11-28 14:08 UTC, pv6 commented on lab2/host/future_weather.cpp
> +    host_pid = host_pid_;
Клиенту у вас приходит не pid хоста, а номер клиента

2020-11-30 13:16 UTC, DariaKrup commented on lab2/host/server.h
> +    server();
Да, архитектура была такой - теперь изменила, убрала client-host connection, связь идет между сервером и client handler'ом через bool переменную и поле std::vector<int> с датой, разложенной по дню, месяцу и году, доступному хендлеру через функцию get_date().
Конструктор и оператор убрала в private блок.

2020-11-30 13:16 UTC, DariaKrup commented on lab2/host/future_weather.cpp
> +    host_pid = host_pid_;
Исправила.

2020-11-30 19:44 UTC, merged