Andrew Kuzin lab2
pv6/OS_Labs_SPBPU_2020 pull request #36
Opened 2020-11-27 00:54 UTC by Kexon5

2020-11-30 16:50 UTC, pv6 requested changes

2020-11-30 16:50 UTC, pv6 commented on kuzin.andrew/lab2/host/Wolf.cpp
> +            pthread_mutex_unlock(&inst.mutex_);
Блокирование мьютексом всей работы потока - оверкилл. Это полностью убивает параллельность, и клиенты получаются обрабатываемыми по очереди.
Критическими участками в данном процессе являются только ожидание хоста и увеличение finishAmount.

2020-11-30 16:50 UTC, pv6 commented on kuzin.andrew/lab2/host/Wolf.cpp
> +    inst.finishAmount_++;
Эта операция тоже должна быть внутри lock unlock

2020-11-30 16:50 UTC, pv6 commented on kuzin.andrew/lab2/host/Wolf.cpp
> +        if (finishAmount_ == clientsAmount_) {
Это условие тоже должно проверятся с использованием pthread_cond_wait, а не просто sleep-ом

2020-12-04 01:08 UTC, Kexon5 commented on kuzin.andrew/lab2/host/Wolf.cpp
> +            pthread_mutex_unlock(&inst.mutex_);
Исправил

2020-12-04 01:09 UTC, Kexon5 commented on kuzin.andrew/lab2/host/Wolf.cpp
> +    inst.finishAmount_++;
Исправил

2020-12-04 01:09 UTC, Kexon5 commented on kuzin.andrew/lab2/host/Wolf.cpp
> +        if (finishAmount_ == clientsAmount_) {
Исправил

2020-12-04 13:42 UTC, pv6 requested changes

2020-12-04 13:42 UTC, pv6 commented on kuzin.andrew/lab2/host/Wolf.cpp
> +            }
Вы разрешаете хосту начинать считать живых козлят раньше, чем был обработан последний клиент (и потенциально не только последний)

2020-12-05 16:09 UTC, Kexon5 commented on kuzin.andrew/lab2/host/Wolf.cpp
> +            }
Исправил.
Также есть проблема с тем, что после разблокировки потоков они все вместе обращаются к одному потоку вывода, тем самым порождая проблему произвольного доступа - эта проблема исправлена, но она в любом случае в решении подразумевает задержку для потоков, поэтому пришлось немного подбить параллельность.

2020-12-08 10:07 UTC, merged