Krupkina.daria
pv6/OS_Labs_SPBPU_2020 pull request #9
Opened 2020-10-26 15:30 UTC by DariaKrup

2020-10-26 17:10 UTC, pv6 requested changes

2020-10-26 17:10 UTC, pv6 commented on lab1/main.cpp
> +    } else if (pid == 0) {
Оба форка лучше делать внутри метода демона

2020-10-26 17:10 UTC, pv6 commented on lab1/daemon.h
> +    static error::error_name init(char* config);
Ссылки и указатели в аргументах следует делать на const в большинстве случаев. Не const будет только если функция явным образом предназначена для изменения значений аргументов. Так что тут должно быть const char*.

Вообще, вы используете std::string для всех остальных строк, поэтому я бы советовал использовать что-то одно.

2020-10-27 17:53 UTC, DariaKrup commented on lab1/main.cpp
> +    } else if (pid == 0) {
Внесла внутрь метода демона

2020-10-27 17:54 UTC, DariaKrup commented on lab1/daemon.h
> +    static error::error_name init(char* config);
Исправила на const std::string&

2020-10-28 15:40 UTC, merged